// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using property_rental.Data;

namespace property_rental.Migrations
{
    [DbContext(typeof(property_rentalContext))]
    partial class property_rentalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("property_rental.model.propery_details", b =>
                {
                    b.Property<int>("property_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("property_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("property_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("property_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("property_value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("property_id");

                    b.ToTable("propery_details");
                });
#pragma warning restore 612, 618
        }
    }
}
